---
title: "Documentation"
author: "Lenka Stastna, Ivana Stanova"
date: "19 11 2020"
output:
  bookdown::html_document2:
    fig_caption: yes
    toc: true
    toc_depth: 2
    number_sections: true
  bookdown::pdf_document2:
    fig_caption: yes
    keep_tex: true
---
Nejaký text z čoho pozostavala praca alebo ustredna tema? Zadanie? kto je sponzor? Kroky?
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 12, fig.height = 8)
library(tidyverse)
library(naniar)
library(styler)
library(GGally)
library(skimr)
library(ggcorrplot)
library(gridExtra)
```

```{r load, eval=TRUE, include=FALSE, cache=TRUE}
data_collection <- read.csv("..\\payment_dates_final.csv")
data_collection <- data_collection %>%
  mutate(due_date = as.Date(due_date, format = "%Y-%m-%d"))
data_collection <- data_collection %>%
  mutate(payment_date = as.Date(payment_date, format = "%Y-%m-%d"))
data_collection <- data_collection %>%
  mutate(product_type = as.factor(product_type))
data_collection <- data_collection %>%
  mutate(contract_status = as.factor(contract_status))
data_collection <- data_collection %>%
  mutate(business_discount = as.factor(business_discount))
data_collection <- data_collection %>%
  mutate(gender = as.factor(gender))
data_collection <- data_collection %>%
  mutate(marital_status = as.factor(marital_status))
data_collection <- data_collection %>%
  mutate(clients_phone = as.factor(clients_phone))
data_collection <- data_collection %>%
  mutate(client_mobile = as.factor(client_mobile))
data_collection <- data_collection %>%
  mutate(client_email = as.factor(client_email))
data_collection <- data_collection %>%
  mutate(total_earnings = factor(total_earnings, labels = c(
    "level1", "level2", "level3", "level4",
    "level5", "level6", "level7", "level8",
    "level9", "level10", "not_declared"
  )))
data_collection <- data_collection %>%
  mutate(living_area = as.factor(living_area))
data_collection <- data_collection %>%
  mutate(different_contact_area = as.factor(different_contact_area))
data_collection <- data_collection %>%
  mutate(kc_flag = as.factor(kc_flag))
data_collection <- data_collection %>%
  mutate(cf_val = as.numeric(cf_val))
data_collection <- data_collection %>%
  mutate(kzmz_flag = as.factor(kzmz_flag))
data_collection <- data_collection %>%
  mutate(due_amount = as.numeric(due_amount))
data_collection <- data_collection %>%
  mutate(paid_amount = as.numeric(payed_ammount))
data_collection <- subset(data_collection, select = -payed_ammount)
data_collection$delay <- difftime(data_collection$payment_date,
  data_collection$due_date, tz,
  units = "days")
```

```{r load_new_data, eval=TRUE, include=FALSE, cache=TRUE}
data_prepared <- read.delim("..\\data_collection_prepared_new.txt", header = TRUE, sep = ";", dec = ".")
data_prepared <- data_prepared %>%
  mutate(delay_140_y = as.factor(delay_140_y))
data_prepared <- data_prepared %>%
  mutate(delay_21_y = as.factor(delay_21_y))
```


```{r Stats, echo=FALSE, eval=TRUE}
# Summary for each attribute
data_prepared <- data_prepared %>% drop_na(delay)

headofTable <- c(
  "Num. of Children", "Num. Other Product", "Year of Birth",
  "Due amount", "Paid amount", "Delay"
)
EX <- c(
  mean(data_collection$number_of_children),
  mean(data_collection$number_other_product), mean(data_collection$birth_year),
  mean(data_collection$due_amount), mean(data_collection$paid_amount),
  mean(data_prepared$delay)
)
VarX <- c(
  var(data_collection$number_of_children),
  var(data_collection$number_other_product), var(data_collection$birth_year),
  var(data_collection$due_amount), var(data_collection$paid_amount),
  var(data_prepared$delay)
)
Median <- c(
  median(data_collection$number_of_children),
  median(data_collection$number_other_product),
  median(data_collection$birth_year), median(data_collection$due_amount),
  median(data_prepared$paid_amount), median(data_collection$delay)
)
Q1 <- c(
  quantile(data_collection$number_of_children, probs = 1 / 4, na.rm = TRUE),
  quantile(data_collection$number_other_product, probs = 1 / 4, na.rm = TRUE),
  quantile(data_collection$birth_year, probs = 1 / 4, na.rm = TRUE),
  quantile(data_collection$due_amount, probs = 1 / 4, na.rm = TRUE),
  quantile(data_collection$paid_amount, probs = 1 / 4, na.rm = TRUE),
  quantile(data_prepared$delay, probs = 1 / 4, na.rm = TRUE)
)
Q3 <- c(
  quantile(data_collection$number_of_children, probs = c(3 / 4), na.rm = TRUE),
  quantile(data_collection$number_other_product, probs = c(3 / 4), na.rm = TRUE),
  quantile(data_collection$birth_year, probs = c(3 / 4), na.rm = TRUE),
  quantile(data_collection$due_amount, probs = c(3 / 4), na.rm = TRUE),
  quantile(data_collection$paid_amount, probs = c(3 / 4), na.rm = TRUE),
  quantile(data_prepared$delay, probs = 3 / 4, na.rm = TRUE)
)
Min <- c(
  min(data_collection$number_of_children),
  min(data_collection$number_other_product),
  min(data_collection$birth_year), min(data_collection$due_amount),
  min(data_prepared$paid_amount), min(data_collection$delay)
)
Max <- c(
  max(data_collection$number_of_children),
  max(data_collection$number_other_product), max(data_collection$birth_year),
  max(data_collection$due_amount), max(data_collection$paid_amount),
  max(data_prepared$delay)
)
summaryData <- distinct(data.frame(headofTable, EX, VarX, Median, Q1, Q3, Min,
  Max,
  check.rows = FALSE, check.names = FALSE
))
knitr::kable(summaryData, caption = "Statistics summary.")
```


